# Generated by Django 2.2.9 on 2020-01-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
