# Generated by Django 2.2.9 on 2020-02-23 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0002_resource_resource_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
    ]
